development:
  adapter: postgresql
  encoding: unicode
  database: mqf_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: mqf_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: mqf_production
  pool: 5
  username: postgres
  password: postgres